version: "3.7"
services:
  app:
    build:      
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: joonik_back
    tty: true
    container_name: joonik_back
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www     
    networks:
      - joonik_back_red
  
  nginx:
    image: nginx:alpine
    tty: true
    container_name: joonik_back_nginx
    restart: always
    ports:
      - 8401:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - joonik_back_red

networks:
  joonik_back_red:
    driver: bridge
